name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the main branch
  pull_request: # Optional: Trigger on pull requests
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/alinorouzifar/imr:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
